### ISSUE TITLE
If you remove a field in the middle it doesn't work well

### ISSUE THREAD

**Issue by PinkBlackEagle** [SaujanBindukar/dynamic-textform-field#1]
Ciao Saujan,

interesting but it doesn't work well.
If you create three fields and enter strings "AAAA" in the first field, "BBBB" in the second field and "CCCC" in the third field and afterwards try to remove the second one with the value "BBBB" the field with value "CCCC" takes the value "BBBB".
Basically if you remove a field in the middle it doesn't work.

Looking at the code it all looks correct, but the behavior is wrong.

Do you have an explanation for this behavior?
Thank you very much!

Francesco

**Comment by SaujanBindukar** [comment]
Hi,
Thanks for reporting the issue. I will look into it and update you as soon
as I can.

Thanks!

**Comment by PinkBlackEagle** [comment]
Ciao Saujan, 
I give you this information.

If the fields you create stay in the "same position" then everything works fine. 
I mean when you press the "delete" button and the TextField is set invisible and everything works correctly. If on the other hand when you press the "remove Text Field" button you recreate the screen without the removed one it seems that FLUTTER gets confused (goes crazy :-)).

If you can do a test you would understand better what I mean.

I really appreciate your articles.

Thank you very much!

**Comment by SaujanBindukar** [comment]
hi @pizzaandspaghetti ,
I have pushed the changes. Please have a review.
Appreciate your comments.
 Thanks
